// Regenerates deploy/seed.sql. The room_units rows come straight from
// data/4SEAS-co-living-room-details-info-9adc9a.xlsx (52 rows); the other
// tables get the minimum rows the app needs to function at all.
//
// Why seeds are mandatory rather than nice-to-have: updateRoom() and
// updateGuide() in app/coliving/admin/actions.ts are UPDATE-only, with no
// insert path anywhere in the codebase. Without a row to update, an admin
// can type the whole Chiang Mai guide, hit save, get no error, and lose
// it. Same for the room cards. So every row the admin is expected to edit
// has to exist up front.
//
// Run: node deploy/gen-seed.mjs
import { read, utils } from 'xlsx'
import { readFileSync, writeFileSync } from 'node:fs'

const q = (v) =>
  v === null || v === undefined || v === '' ? 'NULL' : `'${String(v).replaceAll("'", "''")}'`
const n = (v) => (v === null || v === undefined || v === '' ? 'NULL' : Number(v))

const wb = read(readFileSync('data/4SEAS-co-living-room-details-info-9adc9a.xlsx'))
const raw = utils.sheet_to_json(wb.Sheets.Room_details, { defval: null })

// "Building Name" is a merged cell in the spreadsheet: only the first row
// of each building carries it, so carry it forward.
let building = null
const units = []
for (const r of raw) {
  if (r['Building Name']) building = String(r['Building Name']).trim()
  const roomNo = r['Room N0.']
  if (!building || !roomNo) continue
  units.push({
    building,
    roomNo: String(roomNo).trim(),
    roomType: String(r['Room Type'] ?? '').trim() || 'Unspecified',
    sizeSqm: r['Size (Sqm)'],
    bedType: r['Bed Type'],
    bathroom: r['Bathroom'],
    pax: r['Pax'],
    specialNotes: r['Special Notes'],
  })
}

const unitRows = units
  .map(
    (u, i) =>
      `  (${q(u.building)}, ${q(u.roomNo)}, ${q(u.roomType)}, ${n(u.sizeSqm)}, ` +
      `${q(u.bedType)}, ${q(u.bathroom)}, ${n(u.pax)}, ${q(u.specialNotes)}, true, ${i * 10})`,
  )
  .join(',\n')

const sql = `-- 4Seas Coliving — seed data. Generated by deploy/gen-seed.mjs; edit
-- that script (or the spreadsheet), not this file.
--
-- Idempotent by design: every statement is ON CONFLICT DO NOTHING, so
-- re-running after go-live never overwrites what an admin has edited.

BEGIN;

-- Public room cards. 'third' is special-cased by the admin Settings tab
-- (components/admin/settings-tab.tsx looks up exactly this slug) and
-- ships disabled, matching that form's default. Prices mirror
-- lib/pricing.ts, which is what the cards actually render.
INSERT INTO public.rooms
  (slug, title, description, image_url, image_urls, single_price, double_price, status, enabled, sort_order)
VALUES
  ('nest', 'The Nest Room', NULL, '/rooms/nest-1.jpg',
   '["/rooms/nest-1.jpg","/rooms/nest-2.jpg","/rooms/nest-3.jpg"]',
   1300, 2300, 'available', true, 10),
  ('studio', 'The Studio Room', NULL, '/rooms/studio-1.jpg',
   '["/rooms/studio-1.jpg","/rooms/studio-2.jpg","/rooms/studio-3.jpg"]',
   1300, 2300, 'available', true, 20),
  ('third', 'The Loft Room', NULL, NULL, NULL,
   1300, 2300, 'available', false, 30)
ON CONFLICT (slug) DO NOTHING;

-- Both guide pages degrade to "the guide is being written" when the row
-- is missing, but the admin editor can only UPDATE — so these rows have
-- to exist before anyone can write the content.
INSERT INTO public.guides (slug, title, content) VALUES
  ('chiangmai', 'Chiang Mai Guide',
   E'# Chiang Mai Guide\\n\\nThis guide has not been written yet. Edit it from the admin Knowledge Hub.'),
  ('welcome-internal', 'Resident Onboarding',
   E'# Welcome to 4Seas\\n\\nThis onboarding guide has not been written yet. Edit it from the admin Knowledge Hub.')
ON CONFLICT (slug) DO NOTHING;

-- The Application Hub's quick-reach mail buttons look up exactly these
-- two types (components/admin/applicant-row.tsx). Placeholders are
-- substituted by fillTemplate() in lib/admin-utils.ts: [Name],
-- [Check-in Date], [Check-out Date].
INSERT INTO public.email_templates (type, subject, body) VALUES
  ('need_info', 'A few more details about your 4Seas application',
   E'Hi [Name],\\n\\nThanks for applying to the 4Seas Chiang Mai base. Before we can move forward we need a little more information from you:\\n\\n-\\n\\nJust reply to this email and we will pick it up from there.\\n\\n— 4Seas'),
  ('approved', 'You are in — 4Seas Chiang Mai',
   E'Hi [Name],\\n\\nGood news: your application is approved. We have you down from [Check-in Date] to [Check-out Date].\\n\\nCheck-in details and everything you need for arrival are here: https://4seas.xyz/coliving/checkin\\n\\nSee you in Chiang Mai.\\n\\n— 4Seas')
ON CONFLICT (type) DO NOTHING;

-- ${units.length} physical rooms, imported from
-- data/4SEAS-co-living-room-details-info-9adc9a.xlsx.
INSERT INTO public.room_units
  (building, room_no, room_type, size_sqm, bed_type, bathroom, pax, special_notes, bookable, sort_order)
SELECT v.* FROM (VALUES
${unitRows}
) AS v(building, room_no, room_type, size_sqm, bed_type, bathroom, pax, special_notes, bookable, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM public.room_units);

COMMIT;
`

writeFileSync('deploy/seed.sql', sql)
console.log(`wrote deploy/seed.sql — ${units.length} room_units`)
console.log('buildings:', [...new Set(units.map((u) => u.building))].join(', '))
