-- 4Seas Coliving — seed data. Generated by deploy/gen-seed.mjs; edit
-- that script (or the spreadsheet), not this file.
--
-- Idempotent by design: every statement is ON CONFLICT DO NOTHING, so
-- re-running after go-live never overwrites what an admin has edited.

BEGIN;

-- Public room cards. 'third' is special-cased by the admin Settings tab
-- (components/admin/settings-tab.tsx looks up exactly this slug) and
-- ships disabled, matching that form's default. Prices mirror
-- lib/pricing.ts, which is what the cards actually render.
INSERT INTO public.rooms
  (slug, title, description, image_url, image_urls, single_price, double_price, status, enabled, sort_order)
VALUES
  ('nest', 'The Nest Room', NULL, '/rooms/nest-1.jpg',
   '["/rooms/nest-1.jpg","/rooms/nest-2.jpg","/rooms/nest-3.jpg"]',
   1300, 2300, 'available', true, 10),
  ('studio', 'The Studio Room', NULL, '/rooms/studio-1.jpg',
   '["/rooms/studio-1.jpg","/rooms/studio-2.jpg","/rooms/studio-3.jpg"]',
   1300, 2300, 'available', true, 20),
  ('third', 'The Loft Room', NULL, NULL, NULL,
   1300, 2300, 'available', false, 30)
ON CONFLICT (slug) DO NOTHING;

-- Both guide pages degrade to "the guide is being written" when the row
-- is missing, but the admin editor can only UPDATE — so these rows have
-- to exist before anyone can write the content.
INSERT INTO public.guides (slug, title, content) VALUES
  ('chiangmai', 'Chiang Mai Guide',
   E'# Chiang Mai Guide\n\nThis guide has not been written yet. Edit it from the admin Knowledge Hub.'),
  ('welcome-internal', 'Resident Onboarding',
   E'# Welcome to 4Seas\n\nThis onboarding guide has not been written yet. Edit it from the admin Knowledge Hub.')
ON CONFLICT (slug) DO NOTHING;

-- The Application Hub's quick-reach mail buttons look up exactly these
-- two types (components/admin/applicant-row.tsx). Placeholders are
-- substituted by fillTemplate() in lib/admin-utils.ts: [Name],
-- [Check-in Date], [Check-out Date].
INSERT INTO public.email_templates (type, subject, body) VALUES
  ('need_info', 'A few more details about your 4Seas application',
   E'Hi [Name],\n\nThanks for applying to the 4Seas Chiang Mai base. Before we can move forward we need a little more information from you:\n\n-\n\nJust reply to this email and we will pick it up from there.\n\n— 4Seas'),
  ('approved', 'You are in — 4Seas Chiang Mai',
   E'Hi [Name],\n\nGood news: your application is approved. We have you down from [Check-in Date] to [Check-out Date].\n\nCheck-in details and everything you need for arrival are here: https://4seas.xyz/coliving/checkin\n\nSee you in Chiang Mai.\n\n— 4Seas')
ON CONFLICT (type) DO NOTHING;

-- 52 physical rooms, imported from
-- data/4SEAS-co-living-room-details-info-9adc9a.xlsx.
INSERT INTO public.room_units
  (building, room_no, room_type, size_sqm, bed_type, bathroom, pax, special_notes, bookable, sort_order)
SELECT v.* FROM (VALUES
  ('E', 'E11', 'Big', 40, 'Double bed', 'Shared', 2, NULL, true, 0),
  ('E', 'E12', 'Small', 20, 'Double bed', 'Shared', 1, NULL, true, 10),
  ('E', 'E21', 'Big', 40, 'Double bed', 'Shared', 2, NULL, true, 20),
  ('E', 'E22', 'Small', 20, 'Double bed', 'Shared', 1, NULL, true, 30),
  ('E', 'E31', 'Big', 40, 'Double bed', 'Shared', 2, NULL, true, 40),
  ('E', 'E32', 'Small', 20, 'Double bed', 'Shared', 1, NULL, true, 50),
  ('E', 'E41', 'Big', 40, 'Double bed', 'Shared', 2, NULL, true, 60),
  ('E', 'E42', 'Small', 20, 'Double bed', 'Shared', 1, NULL, true, 70),
  ('F', 'F11', 'Big', 23, 'Twin bed', 'Shared', 2, NULL, true, 80),
  ('F', 'F12', 'Small', 17, 'Double bed', 'Shared', 1, NULL, true, 90),
  ('F', 'F21', 'Big', 23, 'Twin bed', 'Shared', 2, NULL, true, 100),
  ('F', 'F22', 'Small', 17, 'Double bed', 'Shared', 1, NULL, true, 110),
  ('F', 'F31', 'Big', 23, 'Twin bed', 'Shared', 2, NULL, true, 120),
  ('F', 'F32', 'Small', 17, 'Double bed', 'Shared', 1, NULL, true, 130),
  ('Patitta', '103', 'One Bedroom Room Suite', 32, 'Twins/Double bed 7ft.', 'Private (1)', 2, 'Fon''s', true, 140),
  ('Patitta', '202', 'One Bedroom Room Suite', 44, 'Twins/Double bed 7ft.', 'Private (1)', 2, 'Meeting room', true, 150),
  ('Patitta', '203', 'One Bedroom Room Suite', 42, 'Twins/Double bed 7ft.', 'Private (1)', 2, NULL, true, 160),
  ('Patitta', '204', 'One Bedroom Room Suite', 55, 'Twins/Double bed 7ft.', 'Private (1)', 2, 'Break room', true, 170),
  ('Patitta', '205', 'One Bedroom Room Suite', 38, 'Double bed 6ft.', 'Private (1)', 2, NULL, true, 180),
  ('Patitta', '304', 'One Bedroom Room Suite', 55, 'Twins/Double bed 7ft.', 'Private (1)', 2, 'Zik''s room', true, 190),
  ('Patitta', '305', 'One Bedroom Room Suite', 38, 'Twins/Double bed 6ft.', 'Private (1)', 2, NULL, true, 200),
  ('Patitta', '402', 'One Bedroom Room Suite', 44, 'Twins/Double bed 7ft.', 'Private (1)', 2, NULL, true, 210),
  ('Baiyoke', '205', 'Studio Room Suite', 44, 'Double bed', 'Private (1)', 2, NULL, true, 220),
  ('Baiyoke', '206', 'Studio Room Suite', 44, 'Double bed', 'Private (1)', 2, NULL, true, 230),
  ('Baiyoke', '207', 'Studio Room Suite', 44, 'Double bed', 'Private (1)', 2, NULL, true, 240),
  ('Baiyoke', '307', 'Studio Room Suite', 44, 'Double bed', 'Private (1)', 2, NULL, true, 250),
  ('Baiyoke', '407', 'Studio Room Suite', 44, 'Double bed', 'Private (1)', 2, NULL, true, 260),
  ('Baiyoke', '505', 'Studio Room Suite', 44, 'Double bed', 'Private (1)', 2, NULL, true, 270),
  ('Baiyoke', '208', 'Studio Room Suite', 44, 'Twin bed', 'Private (1)', 2, NULL, true, 280),
  ('Baiyoke', '308', 'Studio Room Suite', 44, 'Twin bed', 'Private (1)', 2, NULL, true, 290),
  ('Baiyoke', '408', 'Studio Room Suite', 44, 'Twin bed', 'Private (1)', 2, NULL, true, 300),
  ('Baiyoke', '506', 'Studio Room Suite', 44, 'Twin bed', 'Private (1)', 2, NULL, true, 310),
  ('Baiyoke', '507', 'Studio Room Suite', 44, 'Twin bed', 'Private (1)', 2, NULL, true, 320),
  ('Baiyoke', '201', 'One Bedroom Room Suite', 56, 'Double bed', 'Private (1)', 2, NULL, true, 330),
  ('Baiyoke', '202', 'One Bedroom Room Suite', 56, 'Double bed', 'Private (1)', 2, NULL, true, 340),
  ('Baiyoke', '203', 'One Bedroom Room Suite', 56, 'Double bed', 'Private (1)', 2, NULL, true, 350),
  ('Baiyoke', '302', 'One Bedroom Room Suite', 56, 'Double bed', 'Private (1)', 2, NULL, true, 360),
  ('Baiyoke', '304', 'One Bedroom Room Suite', 56, 'Double bed', 'Private (1)', 2, NULL, true, 370),
  ('Baiyoke', '305', 'One Bedroom Room Suite', 56, 'Double bed', 'Private (1)', 2, NULL, true, 380),
  ('Baiyoke', '306', 'One Bedroom Room Suite', 56, 'Double bed', 'Private (1)', 2, NULL, true, 390),
  ('Baiyoke', '403', 'One Bedroom Room Suite', 56, 'Double bed', 'Private (1)', 2, NULL, true, 400),
  ('Baiyoke', '404', 'One Bedroom Room Suite', 56, 'Double bed', 'Private (1)', 2, NULL, true, 410),
  ('Baiyoke', '406', 'One Bedroom Room Suite', 56, 'Double bed', 'Private (1)', 2, NULL, true, 420),
  ('Baiyoke', '502', 'One Bedroom Room Suite', 56, 'Double bed', 'Private (1)', 2, NULL, true, 430),
  ('Baiyoke', '503', 'One Bedroom Room Suite', 56, 'Double bed', 'Private (1)', 2, NULL, true, 440),
  ('Baiyoke', '301', 'One Bedroom Room Suite', 56, 'Twin bed', 'Private (1)', 2, NULL, true, 450),
  ('Baiyoke', '303', 'One Bedroom Room Suite', 56, 'Twin bed', 'Private (1)', 2, NULL, true, 460),
  ('Baiyoke', '402', 'One Bedroom Room Suite', 56, 'Twin bed', 'Private (1)', 2, NULL, true, 470),
  ('Baiyoke', '405', 'One Bedroom Room Suite', 56, 'Twin bed', 'Private (1)', 2, NULL, true, 480),
  ('Baiyoke', '501', 'One Bedroom Room Suite', 56, 'Twin bed', 'Private (1)', 2, NULL, true, 490),
  ('Baiyoke', '204', 'Two Bedroom Suite', 84, 'Double bed', 'Private (2)', 4, NULL, true, 500),
  ('Baiyoke', '504', 'Two Bedroom Suite', 84, 'Double bed', 'Private (2)', 4, NULL, true, 510)
) AS v(building, room_no, room_type, size_sqm, bed_type, bathroom, pax, special_notes, bookable, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM public.room_units);

COMMIT;
